repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: main
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: main
    hooks:
      - id: prettier
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: golangci-lint
      - id: go-mod-tidy
      - id: go-build
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: main
    hooks:
      - id: eslint
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: master
    hooks:
      - id: shellcheck
