name: test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        go-version: [1.21.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: ./.github/actions/install-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run frontend checks
        run: make frontend-check

      - name: Run backend checks
        run: make backend-check

      - name: Run backend linter
        uses: golangci/golangci-lint-action@v3.7.0

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: >-
            node_modules

      - name: Build
        run: make all

      - name: Health Check
        run: ./voxeti & make health-check

  unit-test-backend:
    name: Run backend unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run unit tests
        run: make backend-unit-test

  e2e-test-backend:
    name: Run backend end-to-end tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run end-to-end tests
        run: make backend-e2e-test

  unit-test-frontend:
    name: Run frontend unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: ./.github/actions/install-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run unit tests
        run: make frontend-unit-test

  e2e-test-frontend:
    name: Run frontend end-to-end tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: ./.github/actions/install-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: pnpm --dir frontend install
        shell: bash

      - name: Install Playwright browsers
        run: pnpm --dir frontend exec playwright install --with-deps

      - name: Run end-to-end tests
        run: make frontend-e2e-test
